### ISSUE TITLE
Payment not received on coinbase

### ISSUE THREAD

**Issue by Vatavuk** [zold-io/wts.zold.io#373]
Ive converted some zolds to bitcoin yesterday but I havent received money on coinbase.
Here is the log
`Zold gem version: 0.29.33/2
WTS version: 0.39.12
Current time is: 2020-08-07T16:11:46Z
Job ID: 0ea55b51-1dc0-493d-8407-7bf2997b836c
Login: vatavuk
Sending 0.0309744 bitcoins to 36PtTAEP5Q1mNBMwWm3sEwGEApizFHc1CX `

**Comment by stepan-romankov** [comment]
I also haven't received BTC since 2 days:

#1	-111.04	2d	e10ec8a0484a52e6	ZLDexchangeto0.03461676BTCat3G4qD3KskKiv87namVVTCjvrkfSbXjx3Hp,rateis0.0002868,feeis0.08,jobIDis53553874-e64f-4b9b-a8d8-0479546e1ff2
#2	-9.66	2d	bc58003401ec577b	Feeforexchangeof0.03461676BTCat3G4qD3KskKiv87namVVTCjvrkfSbXjx3Hp,rateis0.0002868,feeis0.08

Wallet ID: 13839fdf981bb40c

**Comment by yegor256** [comment]
@stepan-romankov I returned 120 ZLD to your wallet

**Comment by yegor256** [comment]
@stepan-romankov full log of the recent trouble is here: https://wts.zold.io/output?id=53553874-e64f-4b9b-a8d8-0479546e1ff2

**Comment by yegor256** [comment]
@stepan-romankov this is the problem: https://github.com/yegor256/sibit/issues/80 I will fix now

**Comment by yegor256** [comment]
@rultor release, tag is `0.39.24`

**Comment by yegor256** [comment]
@stepan-romankov I sent you 120.71 back, sorry for this problem!
